name: ci
on:
  pull_request:
  push:
jobs:
  # x86_64:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Build and Test
  #       run: sh ci/x86_64.sh
  aarch64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: sh ci/aarch64.sh
